### PR TITLE
Feature/beesoft collective UI

### PR DESCRIPTION
**Pull request by thectogeneral**
This should fix the site icon.

### CODE REVIEW

**Comment by brandontrabon** [comment]
You need to merge latest with develop. The PR show every file changed just like the previous one. Did you start this feature branch from develop?

**Review by brandontrabon — CHANGES_REQUESTED** [review]
I should only see changes for the icon; not all of the previous changes from the last PR.

**Comment by thectogeneral** [comment]
@brandontrabon you can review it now.

**Review by brandontrabon — APPROVED** [review]
Looks good

**Pull request merged**
